inherit_from:
  - .rubocop_todo.yml

AllCops:
  RunRailsCops: true # always run the rails cops

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Need to support ruby 1.8
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Style/LineLength:
  Max: 132 # Half of a 1920x1080 screen

Style/MethodLength:
  Max: 20
